# Site settings
title: Meet Hue
email: 
description: >
  Learn everything there is to know about Hue
baseurl: ""
url: "https://meethue.co"
twitter_username:
github_username:

plugins:
  - jekyll-redirect-from

# Build settings
markdown: kramdown

collections:
  products:
    output: true
    permalink: /products/:path/
  guides:
    output: true
    permalink: /guides/:path/
  hacks:
    output: true
    permalink: /hacks/:path/
  apps:
    output: true
    permalink: /apps/:path/

defaults:
  -
    scope:
      type: products
    values:
      layout: product
  -
    scope:
      type: guides
    values:
      layout: guide
      sitemap:
        priority: 0.6
  -
    scope:
      type: hacks
    values:
      layout: hack
      sitemap:
        priority: 0.6
  -
    scope:
      type: apps
    values:
      layout: apps
