# Site settings
title: Meet Hue
email: 
description: >
  Learn everything there is to know about Hue
baseurl: ""
url: "http://meethue.co"
twitter_username:
github_username:

# Build settings
markdown: kramdown

collections:
  products:
    output: true
    permalink: /products/:path/
  guides:
    output: true
    permalink: /guides/:path/
  hacks:
    output: true
    permalink: /hacks/:path/
  software:
    output: true
    permalink: /software/:path/

defaults:
  -
    scope:
      type: products
    values:
      layout: product
  -
    scope:
      type: guides
    values:
      layout: guide
      sitemap:
        priority: 0.6
  -
    scope:
      type: hacks
    values:
      layout: hack
      sitemap:
        priority: 0.6
  -
    scope:
      type: software
    values:
      layout: software
