# Site settings
title: Meet Hue
email: 
description: >
  Learn everything there is to know about Hue
baseurl: ""
url: "http://meethue.co"
twitter_username:
github_username:

# Build settings
markdown: kramdown

collections:
  products:
    output: true
    permalink: /products/:path/
  guides:
    output: true
    permalink: /guides/:path/

defaults:
  -
    scope:
      type: products
    values:
      layout: product
  -
    scope:
      type: guides
    values:
      layout: guide
